### ISSUE TITLE
crc-quota.py does not work for fangping

### ISSUE THREAD

**Issue by fangpingmu** [pitt-crc/wrappers#79]
[fangping@login0b ~]$ crc-quota.py
User: 'fangping'
Traceback (most recent call last):
  File "/ihome/crc/wrappers/crc-quota.py", line 279, in <module>
    CrcQuota().execute()
  File "/ihome/crc/wrappers/_base_parser.py", line 70, in execute
    self.app_logic(args)
  File "/ihome/crc/wrappers/crc-quota.py", line 263, in app_logic
    print(ihome_quota.to_string(args.verbose))
AttributeError: 'NoneType' object has no attribute 'to_string'

**Comment by djperrefort** [comment]
As of version 0.3.1 this bug now manifests as:

```bash
$  crc-quota.py 
Traceback (most recent call last):
  File "/ihome/crc/wrappers/crc-quota.py", line 279, in <module>
    CrcQuota().execute()
  File "/ihome/crc/wrappers/_base_parser.py", line 70, in execute
    self.app_logic(args)
  File "/ihome/crc/wrappers/crc-quota.py", line 257, in app_logic
    supp_quotas = self.get_group_quotas(group)
  File "/ihome/crc/wrappers/crc-quota.py", line 239, in get_group_quotas
    zfs2_quota = GenericUsage.from_path('zfs2', '/zfs2/{}'.format(group))
  File "/ihome/crc/wrappers/crc-quota.py", line 91, in from_path
    quota_info_list = Shell.run_command(df_command).splitlines()
  File "/ihome/crc/wrappers/_utils.py", line 49, in run_command
    err_decoded = std_err.decode().strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
```

This is a Python2/3 compatibility issue. The application works fin in python 3 but is using Python 2.7. I'll update the interpreter (just for the app) and see if that fixes it.

**Comment by djperrefort** [comment]
FWIW this is related to Issue #15. Problems like this should be permanently resolved by PR #65 (which also closes Issue #15)

**Comment by djperrefort** [comment]
I've looked and I don't see your user ID in /ihome/crc/scripts/ihome_quota.json`. The code is erroring because your quota is not being generated by the upstream script.

I'm not very familiar with the upstream code. @iamtroy412 or @buttermutter might have an insight.

**Comment by buttermutter** [comment]
Some sam staff/crc/pitt-it users never had isilon user quotas created for them, to include Fangping.  Instead they would fall under a group quota for sam and/or cssd depending on which directory they write to.  (The isilon acts as though sgid directories are always in effect, where file group ownership defaults to the group owner of the parent directory.)

Using group quotas is an old method of doing things which has been deprecated but there is still some legacy stuff hanging around.

The script used to print 'None' in that case but now throws an exception.

**Comment by djperrefort** [comment]
I'll fix the app and restore the old behavior

**Comment by fangpingmu** [comment]
New bug:

sh: /ihome/crc/wrappers/crc-quota.py: /usr/bin/python3: bad interpreter: No such file or directory

**Comment by fangpingmu** [comment]
It worked yesterday. It does not work on ondemand.htc.crc.pitt.edu. Why do you change python to /usr/bin/python3? This is local python, and we must install the python3 environment on each node. Should we use a python environment installed at /ihome NFS?

**Comment by djperrefort** [comment]
Python 2 and 3 handle the piping of subprocess commands differently. Our current goal is to package the applications in a way that is entirely isolated and doesn't rely on shebang line specifications. Unfortunately, we're a few weeks away from that.

I'll get a quick intermediate fix going.
